#version 450

#include "dequant_head.comp"
#include "iqk_tables.comp"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

#define QUANT_K 256
#define BLOCK_BYTES 100
#define META 4

void main() {
    const uint ib = gl_WorkGroupID.x * 32 + gl_LocalInvocationID.x / 8;
    const uint ib32 = gl_LocalInvocationID.x % 8;

    if (ib >= p.nel / QUANT_K) {
        return;
    }

    const uint nbpb = p.K;
    const uint meta = p.stride_a;
    const uint row_bytes = meta + nbpb * BLOCK_BYTES;
    const uint block_byte = (ib / nbpb) * row_bytes + META + (ib % nbpb) * BLOCK_BYTES;

    const float d = uintBitsToFloat(iqk_load_u32(row_bytes * (ib / nbpb)));
    const uint sc = data_a[block_byte + ib32 % 4] >> (4 * (ib32 / 4));
    const float dl = d * 1.01f * float(sc & 0xFu);

    const uint b_idx = QUANT_K * ib + 32 * ib32;
    const uint ql_off = 4 + 8 * ib32;
    const uint qh_off = 68;
    [[unroll]] for (uint j = 0; j < 4; ++j) {
        uint x = iqk_load_u16(block_byte + ql_off + 2 * j) + 4096u;

        uint sign_mask = 0;
        [[unroll]] for (uint k = 0; k < 4; ++k) {
            sign_mask |= ((data_a[block_byte + qh_off + 8 * j + k] >> ib32) & 1u) << k;
        }
        const vec4 v0 = iqk_hash_values(x, true, sign_mask);

        sign_mask = 0;
        [[unroll]] for (uint k = 0; k < 4; ++k) {
            sign_mask |= ((data_a[block_byte + qh_off + 8 * j + 4 + k] >> ib32) & 1u) << k;
        }
        const vec4 v1 = iqk_hash_values(x, true, sign_mask);

        data_b[b_idx + 8 * j + 0] = D_TYPE(dl * v0.x);
        data_b[b_idx + 8 * j + 1] = D_TYPE(dl * v0.y);
        data_b[b_idx + 8 * j + 2] = D_TYPE(dl * v0.z);
        data_b[b_idx + 8 * j + 3] = D_TYPE(dl * v0.w);
        data_b[b_idx + 8 * j + 4] = D_TYPE(dl * v1.x);
        data_b[b_idx + 8 * j + 5] = D_TYPE(dl * v1.y);
        data_b[b_idx + 8 * j + 6] = D_TYPE(dl * v1.z);
        data_b[b_idx + 8 * j + 7] = D_TYPE(dl * v1.w);
    }
}
