#version 450

#include "dequant_head.comp"
#include "iqk_tables.comp"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

#define QUANT_K 256
#define BLOCK_BYTES 128
#define META 4

void main() {
    const uint ib = gl_WorkGroupID.x * 32 + gl_LocalInvocationID.x / 8;
    const uint ib32 = gl_LocalInvocationID.x % 8;

    if (ib >= p.nel / QUANT_K) {
        return;
    }

    const uint nbpb = p.K;
    const uint meta = p.stride_a;
    const uint row_bytes = meta + nbpb * BLOCK_BYTES;
    const uint block_byte = (ib / nbpb) * row_bytes + META + (ib % nbpb) * BLOCK_BYTES;

    const float d = uintBitsToFloat(iqk_load_u32(block_byte - META));
    const uint qs32 = iqk_load_u32(block_byte + 4 * ib32);
    const float dl = d * (float((qs32 & 0xffu) >> 1) - 64.0f);
    const uint idx0 = ((qs32 & 1u) << 15) + 4096u;

    const uint b_idx = QUANT_K * ib + 32 * ib32;
    const uint ql_off = 32 + 8 * ib32;
    const uint qh_off = 96 + 8 * (ib32 % 4);
    const uint sh_shift = 8 - 4 * (ib32 / 4);

    [[unroll]] for (uint j = 0; j < 8; ++j) {
        const uint sh = qs32 >> (8 + 3 * j);
        uint x = uint(data_a[block_byte + ql_off + j])
               + ((uint(data_a[block_byte + qh_off + j]) << sh_shift) & 0xf00u)
               + ((sh & 7u) << 12)
               + idx0;
        const vec4 v = iqk_hash_values(x, false, 0u);
        data_b[b_idx + 4 * j + 0] = D_TYPE(dl * v.x);
        data_b[b_idx + 4 * j + 1] = D_TYPE(dl * v.y);
        data_b[b_idx + 4 * j + 2] = D_TYPE(dl * v.z);
        data_b[b_idx + 4 * j + 3] = D_TYPE(dl * v.w);
    }
}
